[workspace]
resolver = "3"
members = [
    "wgpucube",
    "xtask",
]
default-members = ["wgpucube"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3"
repository = "https://github.com/tomstokes/wgpucube"
authors = ["Tom Stokes"]
